config/routes.rb
Rails.application.routes.draw do
  get 'static/adDetail'
  root to: "home#show"

  # get "/users/new", to: "users#new"
  # post "/users",    to: "users#create"
  
  resources :users, only: [:new, :create]
  
  #login
  resources :sessions, only: [:new, :create] do
    
    collection do
      delete "sign_out", to: "sessions#destroy", as: "sign_out"  
    end
  end

  #ad
  resources :ads, only: [:new, :create]
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_FORMAT = /[^\s]@[^\s]/
  
  has_secure_password

  validates :name, presence: true 
  validates :email,  format: {with: EMAIL_FORMAT }, uniqueness: true 
  has_many :ads

end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
    before_action :required_logger_user

    def new
        @ad = Ad.new
    end

    def create
        @ad = current_user.ads.build(ad_params)

        # byebug
        unless @ad[:id].blank? && @ad[:title].blank? && @ad[:description].blank? && @ad[:price].blank? && @ad[:images].blank?
            @ad.save
            redirect_to root_path, notice: "Anúcio criado com sucesso!!!"
        else 
            redirect_to new_ad_path, notice: "* Digite todos os valores."
        end
    end

    private
    def ad_params
        params.require(:ad).permit(:title, :description, :price, :images) 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :user_signed_in?, :current_user
    def user_signed_in?
        current_user.present?
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def required_logger_user
        redirect_to new_session_path, alert: "Login necessario!!!" unless user_signed_in?
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def show
        @ads = Ad.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new 
        @user = User.new
    end

    def create 
        user = User.find_by(email: params[:user][:email])

        if user && user.authenticate(params[:user][:password])
            reset_session
            session[:user_id] = user.id
            redirect_to root_path, notice: t(".welcome", name: user.name)
        else
            redirect_to new_session_path, alert: t(".invalid_credentials") 
        end    
    end

    def destroy
        reset_session
        redirect_to new_session_path, notice: t(".session_finished")
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            NotificationMailer.welcome(@user.name, @user.email).deliver_later
            redirect_to new_session_path , notice: t(".success")
        else
            render :new
        end


    end

    private 
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/new.html.erb
<%= form_for @ad, :html => {class: "form_base"} do |form| %>
    <h1 >Anúncio</h1>
    <div class="from_group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "input_base"%>
    </div>
    <div class="from_group">
        <%= form.label :description%>
        <%= form.text_area :description, class: "area-base" %>
    </div>
    <div class="from_group">
        <%= form.label :price%>
        <%= form.number_field :price, class: "input_base"%>
    </div>
    <div class="from_group">
        <%= form.label :images%>
        <%= form.text_area :images , class: "area-base", placeholder: "Digite aa url \nhttps://image.com \nhttps://image-02.com" %>
    </div>
    <div class="from_group">
        <%= form.submit  class: "button_base btn-create" %>
    </div>

<% end %>

app/views/home/show.html.erb
<h1 class="title-pag">Anúncios</h1>
<section>
        <% @ads.each do |ad| %>
            <article>
                <button class="more-info">...</button>
                <div class="content-ad-img">
                    <% ad.images.split(",").each do |img| %>
                        <img src="<%= img %>"  />
                    <% end %>
                </div>
                <div class="content-ad-info">
                    <h3><%= ad.title %></h3>
                    <p><%= ad.description %></p>
                    <p>R$ <%= ad.price %></p>
                </div>

            </article>
        <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classified</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'login', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'home-show', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'new-ad', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <header>
    <div class="logo"> 
      <h1>Logo</h1>
    </div>
      <p class="alert">
        <%= flash.notice %>
        <%= flash.alert %>
      </p>
      <nav>
        <% if user_signed_in? %>
            <%= link_to translate("Home"), root_path, class: "link" %>
            <%= link_to translate("menu.new_ad"), new_ad_path, class: "link" %>
            <%= button_to translate("menu.logout"), sign_out_sessions_path, class: "link_button",  method: :delete %>
        <% else %>
            <%= link_to translate("menu.signin"), new_session_path,  class: "link"  %>
            <%= link_to translate("menu.signup"), new_user_path,  class: "link"  %>
        <% end %>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
   
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <p><%= t("title.error") %> </p>
    <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li> <%= message %> </li>
        <% end %>
    </ul>

<% end %>


<%= form_for @user, url:"/users", :html => {class: "form_base"} do |form| %>
    <h1><%= t("title.signup") %></h1>
    <div class="from_group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "input_base" %>    
    </div>
    <div class="from_group">
        <%= form.label :email %>
        <%= form.email_field :email, class: "input_base" %>    
    </div>
    <div class="from_group">
        <%= form.label :password %>
        <%= form.password_field :password, class: "input_base" %>    
    </div>
    <div class="from_group">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "input_base" %>    
    </div>

    <div class="from_group">
        <%= form.submit  "Cadastrar", class: "button_base btn-login" %>   
    </div>
   
<% end %>